# Generated by Django 4.2 on 2025-11-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='balance',
            new_name='wallet',
        ),
    ]
