# Generated by Django 4.2 on 2025-11-23 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('in_use', 'In Use')], default='active', max_length=20)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_tickets', to='metro.metrostation')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro.metroline')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_tickets', to='metro.metrostation')),
            ],
        ),
    ]
